import pandas as pd
df = pd.read_parquet("E:/quant-research-ofi/features/walk_forward_results.parquet")
pivot_ic = df.pivot_table(index='test_month', columns='ticker', values='ic').sort_index()
print("Mean IC per ticker:")
print(pivot_ic.mean().sort_values(ascending=False).round(4))
print()
print("IC positive folds (out of 7):")
print((pivot_ic > 0).sum().sort_values(ascending=False))
print("Mean gross vs net Sharpe by ticker:")
summary = df.groupby('ticker')[['sharpe_gross', 'sharpe_net']].mean().round(3)
summary['cost_drag'] = (summary['sharpe_gross'] - summary['sharpe_net']).round(3)
print(summary.sort_values('cost_drag', ascending=False))
print("Survival rate by ticker (folds where net Sharpe > 0):")
survival = df.groupby('ticker')['survives'].mean().sort_values(ascending=False)
print((survival * 100).round(1).astype(str) + '%')
